### ISSUE TITLE
[MongoDB] Database creation

### ISSUE THREAD

**Issue by vlad-khrychov** [WebUI-Project-Based-07-nr/BackEnd#17]
Create and connect MongoDB to project.

<img src="https://github.com/ita-social-projects/Space2Study-node-BackEnd-mvp/assets/108689551/796bb7c6-2968-4607-a527-92340140b927" width="400"> 

- Create MongoDB Cluster by using MongoDB Atlas
- Allow IP access from anywhere by setting "zero range" / "all subnets"
- Share connection string with password with your team

⚠️ Don't use personal email for Atlas setup

**Comment by CallMeMaverick** [comment]
MongoDB Atlas cluster has been created using a shared Gmail account. IP access is set to allow connections from anywhere. The connection string and user credentials have been shared in the Discord chat. Env variables in Google Spreadsheets have been updated. Please use these details to connect to the cluster.
