### ISSUE TITLE
(SP: 1) [TinyMCE] Generate token

### ISSUE THREAD

**Issue by nrevutska** [WebUI-Project-Based-07-nr/BackEnd#58]
![image](https://github.com/user-attachments/assets/85154953-7894-40ef-80b8-fdd3acd1922d)

## Description

* Register TinyMCE and generate token
*  Update the environment configuration (`.env`) with the token.

⚠️ Use project email for TinyMCE sign up

**Comment by markgol777** [comment]
Generate what kind of a token? JWT?

**Comment by markgol777** [comment]
done check the board

**Comment by markgol777** [comment]
login info

> email: webuiprojectbased07@gmail.com    
> password: web-c2SZ(HxL2}o9_ui
